/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DelegateCall } from "./DelegateCall";
export type { ERC1155Token } from "./ERC1155Token";
export type { ERC20Token } from "./ERC20Token";
export type { ERC721Token } from "./ERC721Token";
export type { ImmutableStorageTest } from "./ImmutableStorageTest";
