/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IFactoryFriendly,
  IFactoryFriendlyInterface,
} from "../../../contracts/interfaces/IFactoryFriendly";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "initializeParams",
        type: "bytes",
      },
    ],
    name: "setUp",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IFactoryFriendly__factory {
  static readonly abi = _abi;
  static createInterface(): IFactoryFriendlyInterface {
    return new utils.Interface(_abi) as IFactoryFriendlyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFactoryFriendly {
    return new Contract(address, _abi, signerOrProvider) as IFactoryFriendly;
  }
}
