/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IFactoryFriendly__factory } from "./IFactoryFriendly__factory";
export { IMech__factory } from "./IMech__factory";
