/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Account } from "./Account";
export type { Mech } from "./Mech";
export type { Receiver } from "./Receiver";
