/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  DelegateCall,
  DelegateCallInterface,
} from "../../../contracts/test/DelegateCall";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "test",
    outputs: [],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60a060405234801561001057600080fd5b503060805260805160f461002d6000396000603f015260f46000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063f8a8fd6d14602d575b600080fd5b60336035565b005b6001600160a01b037f000000000000000000000000000000000000000000000000000000000000000016300360bc5760405162461bcd60e51b815260206004820152602360248201527f43616e206f6e6c792062652063616c6c6564207669612064656c656761746563604482015262185b1b60ea1b606482015260840160405180910390fd5b56fea2646970667358221220eeb8346d1061aced27d3008a67fbe055faa485cbb69a699dff1519c0ce935fae64736f6c63430008110033";

type DelegateCallConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: DelegateCallConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class DelegateCall__factory extends ContractFactory {
  constructor(...args: DelegateCallConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<DelegateCall> {
    return super.deploy(overrides || {}) as Promise<DelegateCall>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): DelegateCall {
    return super.attach(address) as DelegateCall;
  }
  override connect(signer: Signer): DelegateCall__factory {
    return super.connect(signer) as DelegateCall__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): DelegateCallInterface {
    return new utils.Interface(_abi) as DelegateCallInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DelegateCall {
    return new Contract(address, _abi, signerOrProvider) as DelegateCall;
  }
}
